Add an API for Interests
PolyBooks/sdp_polyBooks pull request #50
Opened 2021-03-12 13:16 UTC by DGoedtkindtEPFL

2021-03-18 20:53 UTC, Snowflake8 commented on app/src/main/java/com/github/polybooks/core/database/Database.kt
> +
A voir si ça marche avec FireBase

2021-03-19 02:51 UTC, RaulinN requested changes

2021-03-19 02:51 UTC, RaulinN commented on app/src/main/java/com/github/polybooks/core/User.kt
> +data class User(val uid : Int, val pseudo : String)
Can you think of something else? Even in the ER-model, we didn't plan for anything else

2021-03-19 02:51 UTC, RaulinN commented on app/src/main/java/com/github/polybooks/core/database/InterestDatabase.kt
> +    fun listAllCourses() : CompletableFuture<List<Field>>
```suggestion
    /**
     * List all the Courses in the database.
     * */
    fun listAllCourses() : CompletableFuture<List<Course>>
```

2021-03-19 15:08 UTC, RaulinN approved these changes
okay with me now :)

2021-03-19 19:39 UTC, Snowflake8 commented on app/src/main/java/com/github/polybooks/core/User.kt
> +data class User(val uid : Int, val pseudo : String)
Interests no?

2021-03-25 19:05 UTC, Snowflake8 approved these changes
Simpler interface, i agree

2021-03-25 19:37 UTC, Huntsekkern approved these changes

2021-03-25 20:44 UTC, Huntsekkern commented
The loss in coverage is negligible (-0.5%). Adding tests for the interface would be nice, but I don't see how before you produce its actual implementation. And I don't think holding this code out of the main branch until the interface is implemented is helpful.

2021-03-26 12:21 UTC, merged